### ISSUE TITLE
출 - 퇴근 페이지

### ISSUE THREAD

**Issue by ksmfou98** [cafenual/cafenual-do#1]
한번 출석이나 퇴근을 눌렀을 경우  그냥 엔터치면 또 눌러짐

**Comment by ksmfou98** [comment]
시간 설정에서  minute 부분이 한자리 일때 01분 02분 이렇게 나와야하는데 1분 2분 이렇게 나옴

**Comment by dongwandonkim** [comment]
> 한번 출석이나 퇴근을 눌렀을 경우 그냥 엔터치면 또 눌러짐

이미 해결하셨을수도있지만 안하셨다면
button -> onClick={e => e.target.blur()}
이거 하시면 클릭 후 버튼에 남아있던 포커스가 빠집니다

**Comment by ksmfou98** [comment]
> > 한번 출석이나 퇴근을 눌렀을 경우 그냥 엔터치면 또 눌러짐
> 
> 이미 해결하셨을수도있지만 안하셨다면
> button -> onClick={e => e.target.blur()}
> 이거 하시면 클릭 후 버튼에 남아있던 포커스가 빠집니다

오 감사합니다 
초점이 남아있어서 그랬군요..
